### ISSUE TITLE
selection tables produced by exp_raven have wrong Begin File and Begin Path when opened in RavenPro1.5

### ISSUE THREAD

**Issue by Gina-maria-cal** [maRce10/Rraven#3] opened 2018-05-23 21:27 UTC
Hello, I am trying to use exp_raven to create a selection table that will open in RavenPro 1.5.  

I used exp_raven to create a .txt sound selection table.  It is one sound selection table file that contains selections from multiple call files.  When I open the sound selection table in a text editor, all the information is correct.  There are 37 different sound files in Begin File and Begin Path columns, each with between 1 and 12 selections.  

[sound_selection_table_pop410.txt](https://github.com/maRce10/Rraven/files/2032842/sound_selection_table_pop410.txt)

When I open this sound selection table in RavenPro 1.5, it seems to correctly sequence the sound files and apply the selections.  The selection table has 388 rows, just as it does in the text editor.  However the information in the Begin File and Begin Path columns is different.  Only the first 11 of the sound files appear in those columns , and they are listed for more than their 12 selections.  I saved the selection table out of Raven:

[sound_selection_table_pop410_postraven.txt](https://github.com/maRce10/Rraven/files/2032865/sound_selection_table_pop410_postraven.txt)

Weirdly, I think it is actually using the correct sound files, and just listing different ones.  When I check the peak frequency of the last row (row 388) in the selection table, it is the peak frequency of the last selection of the 37th sound file (which I opened and checked by entering start and end times by hand).  Whereas the sound selection table as viewed in Raven (sound_selection_table_pop410_postraven.txt) lists Row 388 as the final selection of the 11th sound file (male11_SB.WAV). 

Finally, I don't believe this issue is unique to my particular selection table.  When I use the example files in Rraven, and I open the "Phaethornis multiple sound files.txt" selection table in RavenPro 1.5,  the 
Begin File and Begin Path as viewed in Raven also differ from the contents of the selection table created by exp_raven:  

[Phaethornis multiple sound files.txt](https://github.com/maRce10/Rraven/files/2032890/Phaethornis.multiple.sound.files.txt)
[Phaethornis multiple sound files_postRaven.txt](https://github.com/maRce10/Rraven/files/2032891/Phaethornis.multiple.sound.files_postRaven.txt)

I'd appreciate any thoughts about what might be hapening here.  

By the way, I love the Rraven package, it's really useful.  Audacity exports labels as .txt files with start and end times, so with a little custom programming I'm using Rraven to move between Audacity and Raven.  It's making my life a lot easier!

**Comment by maRce10** [comment] 2018-05-24 02:17
Hi Gina,

thanks for reporting. However, I could not reproduce the error you mentioned with the Rraven example data. This is the "post-raven" file I got:

[Phaethornis.multiple.sound.files_postRaven.txt](https://github.com/maRce10/Rraven/files/2033565/Phaethornis.multiple.sound.files_postRaven.txt)

Everything looks fine. It might be related to the OS. Which OS are you using? (I used Linux)

**Comment by Gina-maria-cal** [comment] 2018-05-24 15:08
Hi, Thanks for your reply!  I'm using Windows.  

In the 'Phaethornis multiple sound files.txt', the Begin file column reads: 
Phae.long1.wav, Phae.long1.wav, Phae.long1.wav, Phae.long2.wav, Phae.long2.wav, Phae.long3.wav, Phae.long3.wav, Phae.long3.wav, Phae.long4.wav, Phae.long4.wav, Phae.long4.wav
(order of sound files is 1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4).  

Whereas, when opened in Raven, and also when saved from Raven (the 'post-raven' file), the Begin file column reads:
Phae.long1.wav, Phae.long1.wav, Phae.long1.wav, Phae.long1.wav, Phae.long1.wav, Phae.long1.wav, Phae.long2.wav, Phae.long1.wav, Phae.long2.wav, Phae.long3.wav, Phae.long2.wav.  

(order of sound files is 1, 1, 1, 1, 1, 1, 2, 1, 2, 3, 2.  The 4th sound file, Phae.long.4.wav, is not present at all.)  This is also what I see when I open the text file you attached to your reply.

**Comment by maRce10** [comment] 2018-05-24 16:05
I am sorry. I attached your "post raven" file. This is the one I got:

[Phaethornis multiple sound files postRaven MAS.txt](https://github.com/maRce10/Rraven/files/2036181/Phaethornis.multiple.sound.files.postRaven.MAS.txt)

**Comment by Gina-maria-cal** [comment] 2018-05-24 18:47
Oh ok, thank you, that does clear up that it is something about my OS or version of Raven or something,  rather than an issue with my data or how I'm using exp_raven, since we are getting different results for the example files.

  I also contacted Raven support, and received the following response.  I'm not sure if this is causing the problem, but thought I'd pass it along in case it's of any use to you.  

"With the information you have presented so far I can't say for certain what is going on, but I have a pretty good guess based on personal experience and the experience of a number of other Raven users. The basic problem is this: a selection table that has the "File Path" and "File Offset" measurements can be opened two ways, as a selection table and as a sound selection table. 

If you open it as a selection table, then Raven will use "Begin Time" and "End Time" to determine where each selection appears in the recording. "Begin Path" and "File Offset" will be overwritten depending on the sound files that were opened in the current sound window. 

If you open it as a sound selection table, then Raven will use "Begin Path" and "File Offset" to determine where each selection appears in the recording. "Begin Time" and "End Time" will be overwritten.

With that background, let me describe the sequence of events that generally gets users into trouble. 

1. The user opens a recording consistenting of several sound files.

2. The user annotated some selections, adds the "Begin Path" and "File Offset" measurements, and saves a selection table.

3. The user opens the selection table as a sound selection table by holding down the Ctrl key while dragging a dropping the selection table, or by selecting File > Open Sound Selection Table from the menu. Before opening the sound selection table, Raven opens only those files in which there was a least one event the last time the selection table was saved. When the selection table opens, the "Begin Time" and "End Time" measurements are overwritten. If there are fewer sound files open than there were in step 2, "Begin Time" and "End Time" will almost certainly be different than they were in step 2.

4. If the user saves the selection table as a sound selection table, and then re-opens it as a regular selection table using the same set of sound files as in step 1, then Raven will use "Begin Time" and "End Time" to determine where they selections appear in the recording, and "Begin Path" and "File Offset" will be overwritten. Now here's the rub: If fewer sound files were open in step 3 than there were in step 2, it is likely that "Begin Path" and "File Offset" will be overwritten with useless values for some of the selections. If the user then saves the selection table, then the placement of some of the events in the recording will be irretrievably lost.

This can be quite unintuitive and easy to mess up. The rule of thumb is once a selection table has been saved as a sound selection table, it must always be opened as a sound selection table. If it is saved as a regular selection table even once, data is likely to be lost."

**Comment by maRce10** [comment] 2018-05-25 00:25
Hmm, interesting. Did you tried that? I actually open the selection table by drag-drop on Raven, so I guess I am opening it as a sound selection table.

**Comment by Gina-maria-cal** [comment] 2018-05-25 12:44
Yes, I tried opening it both as a selection table and a sound selection table, with the same result.  I checked a bunch more measurements from throughout the table, and I'm convinced it is actually generating selections from the correct files, and just over-writing the 'begin file' column with the incorrect file names.  As a workaround, I just used R to merge the added measurements from the table saved in Raven to the table generated with Rraven::exp_raven, to get a dataframe with all the correct info.

**Comment by maRce10** [comment] 2018-05-25 13:03
I see. As a workaround you could add a new column that includes the sound files (and maybe the selection number) but with different column names and that should not be modified by Raven. I will try to run it on Windows to see if there is any other way to fix this. I am closing this issue as it's about Rraven itself

**Closed as completed by maRce10** 2018-05-25 13:03 UTC
